name: CI
on: [push]
jobs:
  build:
    name: Main
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        java-version: [1.8]
        operating-system: [ubuntu-latest]
    steps:
      - name: Prepare
        uses: actions/checkout@v1
      - name: Set Up Java Development Kit
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}
      - name: Maven build clean, build, test and install
        run: |
          mvn clean compile